export const cards = [
  {
    id: 1,
    title: "Thiết Kế Đồ Họa",
    desc: "Thiết Kế Đồ Họa",
    img: "https://images.pexels.com/photos/7532110/pexels-photo-7532110.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 2,
    title: "Thiết Kế Nội Thất",
    desc: "Xây dựng thương hiệu của bạn",
    img: "https://images.pexels.com/photos/11295165/pexels-photo-11295165.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 3,
    title: "Lập trình và Công nghệ",
    desc: "Tùy chỉnh trang web của bạn",
    img: "https://www.jobhopin.com/blog/wp-content/uploads/2020/01/Untitled-design-2.png",
  },
  {
    id: 4,
    title: "Sáng Tạo Nội Dung",
    desc: "Chia sẻ thông điệp của bạn",
    img: "https://images.pexels.com/photos/7608079/pexels-photo-7608079.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 5,
    title: "Video Giới Thiệu",
    desc: "Tương tác với khán giả của bạn",
    img: "https://images.pexels.com/photos/13388047/pexels-photo-13388047.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 6,
    title: "Nhiếp Ảnh",
    desc: "Tiếp cận nhiều khách hàng hơn",
    img: "https://images.pexels.com/photos/11378899/pexels-photo-11378899.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 7,
    title: "Lối sống",
    desc: "Mở khóa sự phát triển trực tuyến",
    img: "https://render.fineartamerica.com/images/images-profile-flow/400/images/artworkimages/mediumlarge/3/male-yoga-art-with-boho-theme-showcases-tranquil-standing-poses-darryl-roach.jpg",
  },
  {
    id: 8,
    title: "Họa Sĩ",
    desc: "Tô màu cho giấc mơ của bạn",
    img: "https://images.pexels.com/photos/15032623/pexels-photo-15032623.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 9,
    title: "Barista và Batender",
    desc: "Pha chế đồ uống",
    img: "https://jerichocoffeetraders.com/cdn/shop/products/barista-training-latte-art_300x.jpg?v=1675932862",
  },
  {
    id: 10,
    title: "Viết lách và Phiên dịch",
    desc: "Thiết Kế Đồ Họa",
    img: "https://images.pexels.com/photos/7532110/pexels-photo-7532110.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
];

export const projects = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1462935/pexels-photo-1462935.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Thiết kế Web và Mobile",
    username: "Nguyễn Thanh Hương",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Thiết kế Logo",
    username: "Nguyễn Minh Tuấn",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Animated GIFs",
    username: "Trần Thị Hương Ly",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Thiết kế Packaging",
    username: "Đinh Văn Phương",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Thiết kế Mạng xã hội",
    username: "Lê Thị An",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Minh họa",
    username: "Phạm Đức Hùng",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Thiết kế Sách",
    username: "Vũ Thị Lan Anh",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Marketing số",
    username: "Nguyễn Văn Nam",
  },
];

export const gigs = [
  {
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Tôi sẽ tạo ra cách bài đang quảng cáo cho sản phẩm của bạn, giúp tăng doanh số mong muốn",
    price: "1.500.000",
    star: 5,
    username: "Nguyễn Ngọc Hoàng Châu",
    revisionNumber: 3,
    deliveryTime: 5,
    shortDesc: "viết content tạo ý tưởng cho sản phẩm",
    shortTitle: "viết content",
    cover: "123456",
    cat: "content creator",
    title: "Viết lách & Phiên dịch",
  },
  {
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Tôi sẽ tạo các mẫu thiết kế poster theo mong đợi khách hàng",
    price: "1.400.000",
    star: 5,
    username: "Nguyễn Thanh Hương",
    revisionNumber: 1,
    deliveryTime: 2,
    shortDesc: "sử dụng các adobe PS, AI, Figma",
    shortTitle: "thiết kế trang web và poster",
    cover: "123456",
    cat: "Thiết Kế Đồ Họa",
    title: "Thiết Kế Đồ Họa",
  },
  {
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Tôi sẽ tạo ra nghệ thuật nhân vật chất lượng cao với AI",
    price: "2.420.000",
    star: 5,
    username: "Nguyễn Minh Tuấn",
    revisionNumber: 1,
    deliveryTime: 2,
    shortDesc: "sử dụng các adobe PS, AI, Figma",
    shortTitle: "thiết kế trang web và poster",
    cover: "123456",
    cat: "Thiết Kế Đồ Họa",
    title: "Thiết Kế Đồ Họa",
  },
  {
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Tôi sẽ tạo ra các bản vẽ duy nhất được tạo bởi AutoCad và các ứng dụng khác",
    price: "10.350.000",
    star: 5,
    username: "Trần Thị Hương Ly",
    revisionNumber: 1,
    deliveryTime: 2,
    shortDesc: "thiết kế nội thất",
    shortTitle: "thiết kế bản vẽ cho một căn nhà",
    cover: "123456",
    cat: "Thiết Kế Nội Thất",
    title: "Thiết Kế Nội Thất",
  },
  {
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Tôi sẽ tạo ra nghệ thuật tùy chỉnh được tạo bởi AutoCad sử dụng ảnh của bạn",
    price: "12.000.000",
    star: 4,
    username: "Đinh Văn Phương",
    revisionNumber: 1,
    deliveryTime: 2,
    shortDesc: "thiết kế nội thất",
    shortTitle: "thiết kế bản vẽ cho một căn nhà",
    cover: "123456789",
    cat: "Thiết Kế Nội Thất",
    title: "Thiết Kế Nội Thất",
  },
  {
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Tôi sẽ tái tạo những giấc mơ của bạn trong hình ảnh chất lượng cao",
    price: "7.000.000",
    star: 5,
    username: "Lê Thị An",
    revisionNumber: 1,
    deliveryTime: 2,
    shortDesc: "chuyên viên tư vấn khách hàng",
    shortTitle: "giải đáp thắc mắc cho khách hàng của mình",
    cover: "123456",
    cat: "Chuyên Viên Tư Vấn",
    title: "Chuyên Viên Tư Vấn",
  },
  {
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Tôi sẽ tạo nghệ thuật kỹ thuật số minh họa bằng trí tuệ nhân tạo siêu thực",
    price: "5.000.000",
    star: 4,
    username: "Phạm Đức Hùng",
    revisionNumber: 1,
    deliveryTime: 2,
    shortDesc:
      "sáng tác các ca khúc nổi tiếng như: Em Gái Mưa, Anh Nhà Ở Đâu Thế,...",
    shortTitle: "sáng tác nhạc",
    cover: "123456",
    cat: "Âm nhạc & Âm thanh",
    title: "Âm nhạc & Âm thanh",
  },
  {
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Tôi từng là quản lý thuộc bộ phận marketing tại công TNHH ABC, giúp công ty phát triển tăng doanh thu vượt bật hằng năm",
    price: "20.000.000",
    star: 3,
    username: "Vũ Thị Lan Anh",
    revisionNumber: 3,
    deliveryTime: 3,
    shortDesc: "Lên kế hoạch kinh doanh giúp tăng doanh thu",
    shortTitle:
      "Phân tích tình hình công ty và đưa ra giải pháp tối ưu chi phí",
    cover: "123456",
    cat: "Kinh doanh",
    title: "Kinh doanh",
  },
  {
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Làm việc tài CityGym, hướng dẫn đào tạo các vận động viên thể hình",
    price: "",
    star: 4,
    username: "Nguyễn Văn Nam",
    revisionNumber: 3,
    deliveryTime: 3,
    shortDesc:
      "Hướng dẫn tập các bài tập thể hình (gym) cải thiện vóc dáng theo đúng quy chuẩn",
    shortTitle: "Hướng dẫn thể dục thể hình",
    cover: "123456",
    cat: "Lối sống",
    title: "Lối sống",
  },
];
